### ISSUE TITLE
Add recommendation around binding to network interfaces

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/sig-security#19]
A discussion from the September 27th SIG meeting concluded that the recommendation from the security SIG should be to always bind to `localhost` rather than to `0.0.0.0` or any interface.

**Comment by EjiroLaurelD** [comment]
Hello @codeboten, may I work on this please?

**Comment by jpkrohling** [comment]
It's yours, @EjiroLaurelD

**Comment by codeboten** [comment]
Thanks @EjiroLaurelD!

**Comment by EjiroLaurelD** [comment]
Thank you

**Comment by codeboten** [comment]
The recommendation is now documented here: https://github.com/open-telemetry/sig-security/blob/main/docs/recommendations.md#binding-to-network-interfaces, closing the issue.
