### ISSUE TITLE
SIG meeting time and frequency

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/sig-security#31]
The weekly security sig meeting is usually fairly quiet as far as attendance. I worry that we may not always have people that can take action in the discussion. Should the meeting time be changed? Is the frequency a problem?

**Comment by oly-baby** [comment]
@codeboten 
Good day,

is this issue open to everyone to work on, if yes, can i work on it

**Comment by jpkrohling** [comment]
I'm fine changing the frequency, perhaps making a strong point of starting discussions early in the Slack channel.

**Comment by cartersocha** [comment]
Biweekly would be nice

**Comment by jpkrohling** [comment]
We haven't been having this meeting for a while now, so I'd like to change the frequency and time slot for this. I'd like to have this bi-weekly at noon UTC, which would make it not conflict with the Collector stability meetings that both me and @codeboten join. I realize that this new time would make it impossible for @codeboten to join, but I'd like to do more frequent huddles on Slack when we need to catch up on something synchronously.
