### ISSUE TITLE
Guidance on signing artifacts in language SDKs

### ISSUE THREAD

**Issue by martinkuba** [open-telemetry/sig-security#48]
The Collector is already signing released images using Sigstore. I think we want to do the same for language SDK releases in general.

I would like to start implementing this in the JavaScript SDK using the [npm provenance](https://docs.npmjs.com/generating-provenance-statements) feature, which is built-in to the npm package manager itself and makes it easy for users to verify how a published package was built.

I am looking for a guidance from the Security SIG on
- whether signing should be implemented by language SDKs
- minimum requirements (e.g. does the npm provenance feature fulfill what we are looking for)

**Comment by tylerbenson** [comment]
While Maven Central doesn't support sigstore/cosign like npm does, I did attempt to implement it for the java sdk repo:
https://github.com/open-telemetry/opentelemetry-java/pull/6531

It would be nice if I could get validation for my approach from the Security SIG, or guidance on what I need to change.

**Comment by jpkrohling** [comment]
@martinkuba, I like very much what I read about NPM with the document you provided me. I wasn't able to find the code behind it, but the documentation has the right things in place: code is signed via github's oauth token, establishing a link between the released artifact and the build, the key is ephemeral (one per build), and the results are stored in the transparency log. 

They even have a summary of those available for users to verify, which I find inspiring: we could have something like that as well!

https://www.npmjs.com/package/sigstore#provenance

![image](https://github.com/open-telemetry/sig-security/assets/13387/07db98ae-45f3-4386-b24d-146bffe51e9c)

**Comment by jpkrohling** [comment]
@tylerbenson , I commented on the PR, and I think you could consider using the Gradle integration. It _could_ be easier to maintain, but your integration doesn't look wrong. I'd appreciate if you could provide some steps for users to perform a verification though, especially given that the tooling around it doesn't seem to support sigstore yet (maven, in particular).

**Comment by jpkrohling** [comment]
I'm closing this, but if you need more info, let me know.
