### ISSUE TITLE
Code Signing and OpenTelemetry Clarification

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/sig-security#72]
This relates to https://github.com/open-telemetry/community/issues/1672 and https://github.com/open-telemetry/community/issues/1671. Is the goal of binary signing to provide chain-of-trust/sbom attestations, or are we trying to avoid UAC popups or macOS signature checks? If it is the former, then cosign should work. If it is the latter, there does not appear to be a way to do this easily or at all. EV certificates not only cost money, but new requirements would require HSM for keymatter storage (this would probably necessitate provisioning vault or using something in our oracle cloud account). 

Would appreciate clarification on this before we go any further from an infra perspective.

**Comment by jpkrohling** [comment]
We have focused on cosign/sigstore (ie, keyless) attestations/signing. We have historically stayed away from traditional code signing, as it's hard to achieve that in a open, transparent, and trusted way. I believe @pjanotti has done some work on that for Windows, and we may end up using the lessons learned to formalize a recommendation, but we are not there yet.

**Comment by austinlparker** [comment]
So, should we close those community issues then, if we're not going to do traditional code signing?

**Comment by jpkrohling** [comment]
No, they should still be open to gauge interest and drive an initial work. Once we have enough interest and experience doing that for a couple of SIGs, we can turn that into a recommendation.
