### ISSUE TITLE
Create CVEE disclosure on OTel website

### ISSUE THREAD

**Issue by cartersocha** [open-telemetry/sig-security#8]
Copy CVEE disclosure from kubernetes and start public incident discloure

**Comment by jpkrohling** [comment]
@cartersocha, is this what you had in mind? https://kubernetes.io/docs/reference/issues-security/official-cve-feed/

**Comment by jpkrohling** [comment]
From that page, I eventually landed here, which has many things we could use as base as well: https://github.com/kubernetes/committee-security-response/tree/main
